services:
  manager:
    build: .
    hostname: manager
    working_dir: /etc/jackadi
    environment:
      - JACKADI_MANAGER_ADDRESS=0.0.0.0
      - JACKADI_MANAGER_AUTO_ACCEPT_NODE=true
      - JACKADI_MANAGER_MTLS_CERT=/etc/jackadi/tls/manager_cert.pem
      - JACKADI_MANAGER_MTLS_KEY=/etc/jackadi/tls/manager_key.pem
      - JACKADI_MANAGER_MTLS_NODE_CA_CERT=/etc/jackadi/tls/node_ca_cert.pem
      - JACKADI_MANAGER_API_ADDRESS=0.0.0.0
    command: sh -c "\
      jack completion bash > /etc/bash_completion.d/_jack && \
      exec jackadi-manager"
    volumes:
      - ./demo.sh:/etc/jackadi/demo.sh
      - ./manager:/usr/bin/jackadi-manager
      - ./plugins/:/opt/jackadi/plugins/
      - ./plugins.yaml:/etc/jackadi/plugins.yaml
      - ./authorization.yaml:/etc/jackadi/authorization.yaml
      - ./htpasswd:/etc/jackadi/.htpasswd
      - ./jack:/usr/bin/jack
      - ./tls/manager_cert.pem:/etc/jackadi/tls/manager_cert.pem
      - ./tls/manager_key.pem:/etc/jackadi/tls/manager_key.pem
      - ./tls/node_ca_cert.pem:/etc/jackadi/tls/node_ca_cert.pem
    ports:
      - 127.0.0.1:8081:8081

  node1:
    image: ubuntu
    hostname: node1
    working_dir: /etc/jackadi
    environment:
      - JACKADI_NODE_NODE_ID=node1
      - JACKADI_NODE_MANAGER_ADDRESS=manager
      - JACKADI_NODE_MTLS_CERT=/etc/jackadi/tls/node1_cert.pem
      - JACKADI_NODE_MTLS_KEY=/etc/jackadi/tls/node1_key.pem
      - JACKADI_NODE_MTLS_MANAGER_CA_CERT=/etc/jackadi/tls/manager_ca_cert.pem
    command: jackadi-node
    volumes:
      - ./node/:/usr/bin/jackadi-node
      - ./tls/node1_cert.pem:/etc/jackadi/tls/node1_cert.pem
      - ./tls/node1_key.pem:/etc/jackadi/tls/node1_key.pem
      - ./tls/manager_ca_cert.pem:/etc/jackadi/tls/manager_ca_cert.pem

  node2:
    image: ubuntu
    hostname: node2
    working_dir: /etc/jackadi
    environment:
      - JACKADI_NODE_NODE_ID=node2
      - JACKADI_NODE_MANAGER_ADDRESS=manager
      - JACKADI_NODE_MTLS_ENABLED=true
      - JACKADI_NODE_MTLS_CERT=/etc/jackadi/tls/node2_cert.pem
      - JACKADI_NODE_MTLS_KEY=/etc/jackadi/tls/node2_key.pem
      - JACKADI_NODE_MTLS_MANAGER_CA_CERT=/etc/jackadi/tls/manager_ca_cert.pem
    command: jackadi-node
    volumes:
      - ./node/:/usr/bin/jackadi-node
      - ./tls/node2_cert.pem:/etc/jackadi/tls/node2_cert.pem
      - ./tls/node2_key.pem:/etc/jackadi/tls/node2_key.pem
      - ./tls/manager_ca_cert.pem:/etc/jackadi/tls/manager_ca_cert.pem