// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: internal/proto/api.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter int32

const (
	Filter_NONE            Filter = 0
	Filter_ONLY_ACCEPTED   Filter = 1
	Filter_ONLY_CANDIDATES Filter = 2
	Filter_ONLY_REJECTED   Filter = 3
)

// Enum value maps for Filter.
var (
	Filter_name = map[int32]string{
		0: "NONE",
		1: "ONLY_ACCEPTED",
		2: "ONLY_CANDIDATES",
		3: "ONLY_REJECTED",
	}
	Filter_value = map[string]int32{
		"NONE":            0,
		"ONLY_ACCEPTED":   1,
		"ONLY_CANDIDATES": 2,
		"ONLY_REJECTED":   3,
	}
)

func (x Filter) Enum() *Filter {
	p := new(Filter)
	*p = x
	return p
}

func (x Filter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Filter) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_api_proto_enumTypes[0].Descriptor()
}

func (Filter) Type() protoreflect.EnumType {
	return &file_internal_proto_api_proto_enumTypes[0]
}

func (x Filter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Filter.Descriptor instead.
func (Filter) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{0}
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        Filter                 `protobuf:"varint,1,opt,name=filter,proto3,enum=proto.Filter" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *ListAgentsRequest) GetFilter() Filter {
	if x != nil {
		return x.Filter
	}
	return Filter_NONE
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      []*AgentInfo           `protobuf:"bytes,1,rep,name=accepted,proto3" json:"accepted,omitempty"`
	Candidates    []*AgentInfo           `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Rejected      []*AgentInfo           `protobuf:"bytes,3,rep,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *ListAgentsResponse) GetAccepted() []*AgentInfo {
	if x != nil {
		return x.Accepted
	}
	return nil
}

func (x *ListAgentsResponse) GetCandidates() []*AgentInfo {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *ListAgentsResponse) GetRejected() []*AgentInfo {
	if x != nil {
		return x.Rejected
	}
	return nil
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       *string                `protobuf:"bytes,2,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Certificate   *string                `protobuf:"bytes,3,opt,name=certificate,proto3,oneof" json:"certificate,omitempty"`
	IsConnected   *bool                  `protobuf:"varint,4,opt,name=isConnected,proto3,oneof" json:"isConnected,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=since,proto3,oneof" json:"since,omitempty"`
	LastMsg       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=lastMsg,proto3,oneof" json:"lastMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_internal_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *AgentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentInfo) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *AgentInfo) GetCertificate() string {
	if x != nil && x.Certificate != nil {
		return *x.Certificate
	}
	return ""
}

func (x *AgentInfo) GetIsConnected() bool {
	if x != nil && x.IsConnected != nil {
		return *x.IsConnected
	}
	return false
}

func (x *AgentInfo) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *AgentInfo) GetLastMsg() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMsg
	}
	return nil
}

type AgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentInfo             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *AgentRequest) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

type AgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentInfo             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *AgentResponse) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

type AgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentsResponse) Reset() {
	*x = AgentsResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentsResponse) ProtoMessage() {}

func (x *AgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentsResponse.ProtoReflect.Descriptor instead.
func (*AgentsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *AgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

type ResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultID      string                 `protobuf:"bytes,1,opt,name=resultID,proto3" json:"resultID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultsRequest) Reset() {
	*x = ResultsRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultsRequest) ProtoMessage() {}

func (x *ResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultsRequest.ProtoReflect.Descriptor instead.
func (*ResultsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *ResultsRequest) GetResultID() string {
	if x != nil {
		return x.ResultID
	}
	return ""
}

type ResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // raw result, as stored in the DB (should be a serialized JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultsResponse) Reset() {
	*x = ResultsResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultsResponse) ProtoMessage() {}

func (x *ResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultsResponse.ProtoReflect.Descriptor instead.
func (*ResultsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *ResultsResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type RequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestID     string                 `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRequest) Reset() {
	*x = RequestRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRequest) ProtoMessage() {}

func (x *RequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRequest.ProtoReflect.Descriptor instead.
func (*RequestRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *RequestRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

type RequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"` // raw request, as stored in the DB (should be a serialized JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestResponse) Reset() {
	*x = RequestResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestResponse) ProtoMessage() {}

func (x *RequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestResponse.ProtoReflect.Descriptor instead.
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *RequestResponse) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type ListResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`                           // Starting position for pagination (0-based)
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                             // Maximum number of results to return, defaults to 100 if not specified
	FromDate      *int64                 `protobuf:"varint,3,opt,name=from_date,json=fromDate,proto3,oneof" json:"from_date,omitempty"` // Optional Unix timestamp to filter results from this date
	ToDate        *int64                 `protobuf:"varint,4,opt,name=to_date,json=toDate,proto3,oneof" json:"to_date,omitempty"`       // Optional Unix timestamp to filter results up to this date
	Targets       []string               `protobuf:"bytes,5,rep,name=targets,proto3" json:"targets,omitempty"`                          // Optional list of agent IDs to filter results by targets
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResultsRequest) Reset() {
	*x = ListResultsRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResultsRequest) ProtoMessage() {}

func (x *ListResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResultsRequest.ProtoReflect.Descriptor instead.
func (*ListResultsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *ListResultsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListResultsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListResultsRequest) GetFromDate() int64 {
	if x != nil && x.FromDate != nil {
		return *x.FromDate
	}
	return 0
}

func (x *ListResultsRequest) GetToDate() int64 {
	if x != nil && x.ToDate != nil {
		return *x.ToDate
	}
	return 0
}

func (x *ListResultsRequest) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

type ResultEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Agent         string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // Status of the task (success, failed, error)
	InternalError InternalError          `protobuf:"varint,4,opt,name=internal_error,json=internalError,proto3,enum=proto.InternalError" json:"internal_error,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultEntry) Reset() {
	*x = ResultEntry{}
	mi := &file_internal_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultEntry) ProtoMessage() {}

func (x *ResultEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultEntry.ProtoReflect.Descriptor instead.
func (*ResultEntry) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *ResultEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResultEntry) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *ResultEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResultEntry) GetInternalError() InternalError {
	if x != nil {
		return x.InternalError
	}
	return InternalError_OK
}

func (x *ResultEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ResultEntry         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResultsResponse) Reset() {
	*x = ListResultsResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResultsResponse) ProtoMessage() {}

func (x *ListResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResultsResponse.ProtoReflect.Descriptor instead.
func (*ListResultsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *ListResultsResponse) GetResults() []*ResultEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_internal_proto_api_proto protoreflect.FileDescriptor

const file_internal_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x18internal/proto/api.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18internal/proto/msg.proto\":\n" +
	"\x11ListAgentsRequest\x12%\n" +
	"\x06filter\x18\x01 \x01(\x0e2\r.proto.FilterR\x06filter\"\xa2\x01\n" +
	"\x12ListAgentsResponse\x12,\n" +
	"\baccepted\x18\x01 \x03(\v2\x10.proto.AgentInfoR\baccepted\x120\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x10.proto.AgentInfoR\n" +
	"candidates\x12,\n" +
	"\brejected\x18\x03 \x03(\v2\x10.proto.AgentInfoR\brejected\"\xbc\x02\n" +
	"\tAgentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\aaddress\x18\x02 \x01(\tH\x00R\aaddress\x88\x01\x01\x12%\n" +
	"\vcertificate\x18\x03 \x01(\tH\x01R\vcertificate\x88\x01\x01\x12%\n" +
	"\visConnected\x18\x04 \x01(\bH\x02R\visConnected\x88\x01\x01\x125\n" +
	"\x05since\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x05since\x88\x01\x01\x129\n" +
	"\alastMsg\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x04R\alastMsg\x88\x01\x01B\n" +
	"\n" +
	"\b_addressB\x0e\n" +
	"\f_certificateB\x0e\n" +
	"\f_isConnectedB\b\n" +
	"\x06_sinceB\n" +
	"\n" +
	"\b_lastMsg\"6\n" +
	"\fAgentRequest\x12&\n" +
	"\x05agent\x18\x01 \x01(\v2\x10.proto.AgentInfoR\x05agent\"7\n" +
	"\rAgentResponse\x12&\n" +
	"\x05agent\x18\x01 \x01(\v2\x10.proto.AgentInfoR\x05agent\":\n" +
	"\x0eAgentsResponse\x12(\n" +
	"\x06agents\x18\x01 \x03(\v2\x10.proto.AgentInfoR\x06agents\",\n" +
	"\x0eResultsRequest\x12\x1a\n" +
	"\bresultID\x18\x01 \x01(\tR\bresultID\")\n" +
	"\x0fResultsResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\".\n" +
	"\x0eRequestRequest\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\"+\n" +
	"\x0fRequestResponse\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\"\xb6\x01\n" +
	"\x12ListResultsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12 \n" +
	"\tfrom_date\x18\x03 \x01(\x03H\x00R\bfromDate\x88\x01\x01\x12\x1c\n" +
	"\ato_date\x18\x04 \x01(\x03H\x01R\x06toDate\x88\x01\x01\x12\x18\n" +
	"\atargets\x18\x05 \x03(\tR\atargetsB\f\n" +
	"\n" +
	"_from_dateB\n" +
	"\n" +
	"\b_to_date\"\x9e\x01\n" +
	"\vResultEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12;\n" +
	"\x0einternal_error\x18\x04 \x01(\x0e2\x14.proto.InternalErrorR\rinternalError\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"C\n" +
	"\x13ListResultsResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.proto.ResultEntryR\aresults*M\n" +
	"\x06Filter\x12\b\n" +
	"\x04NONE\x10\x00\x12\x11\n" +
	"\rONLY_ACCEPTED\x10\x01\x12\x13\n" +
	"\x0fONLY_CANDIDATES\x10\x02\x12\x11\n" +
	"\rONLY_REJECTED\x10\x032\xfb\x04\n" +
	"\x03API\x12Z\n" +
	"\n" +
	"ListAgents\x12\x18.proto.ListAgentsRequest\x1a\x19.proto.ListAgentsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/agents/list\x12V\n" +
	"\vAcceptAgent\x12\x13.proto.AgentRequest\x1a\x14.proto.AgentResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/agents/accept\x12T\n" +
	"\vRemoveAgent\x12\x13.proto.AgentRequest\x1a\x15.proto.AgentsResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/agents/remove\x12W\n" +
	"\vRejectAgent\x12\x13.proto.AgentRequest\x1a\x15.proto.AgentsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/agents/reject\x12W\n" +
	"\n" +
	"GetResults\x12\x15.proto.ResultsRequest\x1a\x16.proto.ResultsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/results/result\x12^\n" +
	"\vListResults\x12\x19.proto.ListResultsRequest\x1a\x1a.proto.ListResultsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/results/list\x12X\n" +
	"\n" +
	"GetRequest\x12\x15.proto.RequestRequest\x1a\x16.proto.RequestResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/results/requestB.Z,github.com/jackadi-io/jackadi/internal/protob\x06proto3"

var (
	file_internal_proto_api_proto_rawDescOnce sync.Once
	file_internal_proto_api_proto_rawDescData []byte
)

func file_internal_proto_api_proto_rawDescGZIP() []byte {
	file_internal_proto_api_proto_rawDescOnce.Do(func() {
		file_internal_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_api_proto_rawDesc), len(file_internal_proto_api_proto_rawDesc)))
	})
	return file_internal_proto_api_proto_rawDescData
}

var file_internal_proto_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_proto_api_proto_goTypes = []any{
	(Filter)(0),                   // 0: proto.Filter
	(*ListAgentsRequest)(nil),     // 1: proto.ListAgentsRequest
	(*ListAgentsResponse)(nil),    // 2: proto.ListAgentsResponse
	(*AgentInfo)(nil),             // 3: proto.AgentInfo
	(*AgentRequest)(nil),          // 4: proto.AgentRequest
	(*AgentResponse)(nil),         // 5: proto.AgentResponse
	(*AgentsResponse)(nil),        // 6: proto.AgentsResponse
	(*ResultsRequest)(nil),        // 7: proto.ResultsRequest
	(*ResultsResponse)(nil),       // 8: proto.ResultsResponse
	(*RequestRequest)(nil),        // 9: proto.RequestRequest
	(*RequestResponse)(nil),       // 10: proto.RequestResponse
	(*ListResultsRequest)(nil),    // 11: proto.ListResultsRequest
	(*ResultEntry)(nil),           // 12: proto.ResultEntry
	(*ListResultsResponse)(nil),   // 13: proto.ListResultsResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(InternalError)(0),            // 15: proto.InternalError
}
var file_internal_proto_api_proto_depIdxs = []int32{
	0,  // 0: proto.ListAgentsRequest.filter:type_name -> proto.Filter
	3,  // 1: proto.ListAgentsResponse.accepted:type_name -> proto.AgentInfo
	3,  // 2: proto.ListAgentsResponse.candidates:type_name -> proto.AgentInfo
	3,  // 3: proto.ListAgentsResponse.rejected:type_name -> proto.AgentInfo
	14, // 4: proto.AgentInfo.since:type_name -> google.protobuf.Timestamp
	14, // 5: proto.AgentInfo.lastMsg:type_name -> google.protobuf.Timestamp
	3,  // 6: proto.AgentRequest.agent:type_name -> proto.AgentInfo
	3,  // 7: proto.AgentResponse.agent:type_name -> proto.AgentInfo
	3,  // 8: proto.AgentsResponse.agents:type_name -> proto.AgentInfo
	15, // 9: proto.ResultEntry.internal_error:type_name -> proto.InternalError
	12, // 10: proto.ListResultsResponse.results:type_name -> proto.ResultEntry
	1,  // 11: proto.API.ListAgents:input_type -> proto.ListAgentsRequest
	4,  // 12: proto.API.AcceptAgent:input_type -> proto.AgentRequest
	4,  // 13: proto.API.RemoveAgent:input_type -> proto.AgentRequest
	4,  // 14: proto.API.RejectAgent:input_type -> proto.AgentRequest
	7,  // 15: proto.API.GetResults:input_type -> proto.ResultsRequest
	11, // 16: proto.API.ListResults:input_type -> proto.ListResultsRequest
	9,  // 17: proto.API.GetRequest:input_type -> proto.RequestRequest
	2,  // 18: proto.API.ListAgents:output_type -> proto.ListAgentsResponse
	5,  // 19: proto.API.AcceptAgent:output_type -> proto.AgentResponse
	6,  // 20: proto.API.RemoveAgent:output_type -> proto.AgentsResponse
	6,  // 21: proto.API.RejectAgent:output_type -> proto.AgentsResponse
	8,  // 22: proto.API.GetResults:output_type -> proto.ResultsResponse
	13, // 23: proto.API.ListResults:output_type -> proto.ListResultsResponse
	10, // 24: proto.API.GetRequest:output_type -> proto.RequestResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_proto_api_proto_init() }
func file_internal_proto_api_proto_init() {
	if File_internal_proto_api_proto != nil {
		return
	}
	file_internal_proto_msg_proto_init()
	file_internal_proto_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_internal_proto_api_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_api_proto_rawDesc), len(file_internal_proto_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_api_proto_goTypes,
		DependencyIndexes: file_internal_proto_api_proto_depIdxs,
		EnumInfos:         file_internal_proto_api_proto_enumTypes,
		MessageInfos:      file_internal_proto_api_proto_msgTypes,
	}.Build()
	File_internal_proto_api_proto = out.File
	file_internal_proto_api_proto_goTypes = nil
	file_internal_proto_api_proto_depIdxs = nil
}
